name: Release project
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        id: release
        uses: huggingface/semver-release-action@latest
        with:
          branches: '["main", {"name": "beta", "prerelease": true}, {"name": "alpha", "prerelease": true}]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ steps.release.outputs.changelog }}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git commit -am "chore(release-${{ steps.release.outputs.version }}): Update CHANGELOG.md"
          git push
