name: Release project
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    permissions:
        contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: qoomon/setup-git@v1

      - name: Release
        id: release
        uses: huggingface/semver-release-action@latest
        with:
          branches: '["main", {"name": "beta", "prerelease": true}, {"name": "alpha", "prerelease": true}]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        if: github.ref == 'refs/heads/main' && steps.release.outputs.version
        run: |
          echo "${{ steps.release.outputs.changelog }}" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore(release): Update CHANGELOG.md for ${{ steps.release.outputs.version }}"
          git push
