name: Release project
on:
    push:
        branches:
            - main
            - beta
            - alpha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        id: release
        uses: huggingface/semver-release-action@latest
        with:
          branches: '["main", "beta", "alpha"]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: print outputs
        run: |
          echo "The new version is ${{ steps.release.outputs.version }}"
          echo "The release tag is ${{ steps.release.outputs.tag }}"
          echo "The release changelog is ${{ steps.release.outputs.changelog }}"
